import { MigrationInterface, QueryRunner } from 'typeorm'

export class Init1559521377715 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "tags" ("name" text PRIMARY KEY NOT NULL)`)
        await queryRunner.query(`CREATE TABLE "posts" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "deleted_at" datetime, "nonce" integer NOT NULL, "position" integer NOT NULL, "type" text NOT NULL, "content" text, "parent_txid" text, "sender_address" text)`)
        await queryRunner.query(`CREATE INDEX "IDX_60818528127866f5002e7f826d" ON "posts" ("created_at") `)
        await queryRunner.query(`CREATE INDEX "IDX_862deee3599ab1a65f8d6a4845" ON "posts" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_560752d45d78a3332853345e32" ON "posts" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_a56e2db14676f90be1694e2723" ON "posts" ("parent_txid") `)
        await queryRunner.query(`CREATE INDEX "IDX_565d3e71ac2ea22a54a0631994" ON "posts" ("sender_address") `)
        await queryRunner.query(`CREATE TABLE "users" ("address" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "birth_block" bigint NOT NULL, "name" text NOT NULL, "bio" text, "avatar_link" text)`)
        await queryRunner.query(`CREATE INDEX "IDX_1b4832240d11291453c40c3281" ON "users" ("birth_block") `)
        await queryRunner.query(`CREATE TABLE "orphans" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "block_height" bigint NOT NULL, "nonce" integer, "position" integer, "type" text NOT NULL, "content" text, "reference_id" text, "reference_sender_address" text, "mentions" text, "sender_address" text)`)
        await queryRunner.query(`CREATE INDEX "IDX_4149b5d28a9d574cb35ac0b880" ON "orphans" ("created_at") `)
        await queryRunner.query(`CREATE INDEX "IDX_08f49bf2cacd532e2e10eb5779" ON "orphans" ("block_height") `)
        await queryRunner.query(`CREATE INDEX "IDX_2ccda451e12bc68c5af8d3c9b4" ON "orphans" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_17be0dbba5ea05d3c431737ba8" ON "orphans" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_617a3a43a298c164330279390c" ON "orphans" ("reference_id") `)
        await queryRunner.query(`CREATE INDEX "IDX_1d57610e4bf65bca7df9f747be" ON "orphans" ("reference_sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_d8dc419b6ee03babf580a7b3c3" ON "orphans" ("sender_address") `)
        await queryRunner.query(`CREATE TABLE "tx_blocks" ("height" bigint PRIMARY KEY NOT NULL, "hash" text NOT NULL, CONSTRAINT "UQ_d16046b3c22e0ac37b9367ba8d4" UNIQUE ("hash"))`)
        await queryRunner.query(`CREATE INDEX "IDX_d16046b3c22e0ac37b9367ba8d" ON "tx_blocks" ("hash") `)
        await queryRunner.query(`CREATE TABLE "utxos" ("txid" text NOT NULL, "position" integer NOT NULL, "block_height" bigint NOT NULL, "address" text NOT NULL, "value" bigint NOT NULL, "raw" text NOT NULL, PRIMARY KEY ("txid", "position"))`)
        await queryRunner.query(`CREATE INDEX "IDX_f4ddf5596761915d4415c18040" ON "utxos" ("block_height") `)
        await queryRunner.query(`CREATE INDEX "IDX_7ee003620e5c4dc41c8020c3a4" ON "utxos" ("address") `)
        await queryRunner.query(`CREATE TABLE "post_tags" ("tag_name" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("tag_name", "post_txid"))`)
        await queryRunner.query(`CREATE TABLE "follows" ("followed_address" text NOT NULL, "follower_address" text NOT NULL, PRIMARY KEY ("followed_address", "follower_address"))`)
        await queryRunner.query(`CREATE TABLE "blocks" ("blocked_address" text NOT NULL, "blocker_address" text NOT NULL, PRIMARY KEY ("blocked_address", "blocker_address"))`)
        await queryRunner.query(`CREATE TABLE "likes" ("user_address" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`CREATE TABLE "flags" ("user_address" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`CREATE TABLE "mentions" ("user_address" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`DROP INDEX "IDX_60818528127866f5002e7f826d"`)
        await queryRunner.query(`DROP INDEX "IDX_862deee3599ab1a65f8d6a4845"`)
        await queryRunner.query(`DROP INDEX "IDX_560752d45d78a3332853345e32"`)
        await queryRunner.query(`DROP INDEX "IDX_a56e2db14676f90be1694e2723"`)
        await queryRunner.query(`DROP INDEX "IDX_565d3e71ac2ea22a54a0631994"`)
        await queryRunner.query(`CREATE TABLE "temporary_posts" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "deleted_at" datetime, "nonce" integer NOT NULL, "position" integer NOT NULL, "type" text NOT NULL, "content" text, "parent_txid" text, "sender_address" text, CONSTRAINT "FK_a56e2db14676f90be1694e27235" FOREIGN KEY ("parent_txid") REFERENCES "posts" ("txid"), CONSTRAINT "FK_565d3e71ac2ea22a54a0631994b" FOREIGN KEY ("sender_address") REFERENCES "users" ("address"))`)
        await queryRunner.query(`INSERT INTO "temporary_posts"("txid", "created_at", "deleted_at", "nonce", "position", "type", "content", "parent_txid", "sender_address") SELECT "txid", "created_at", "deleted_at", "nonce", "position", "type", "content", "parent_txid", "sender_address" FROM "posts"`)
        await queryRunner.query(`DROP TABLE "posts"`)
        await queryRunner.query(`ALTER TABLE "temporary_posts" RENAME TO "posts"`)
        await queryRunner.query(`CREATE INDEX "IDX_60818528127866f5002e7f826d" ON "posts" ("created_at") `)
        await queryRunner.query(`CREATE INDEX "IDX_862deee3599ab1a65f8d6a4845" ON "posts" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_560752d45d78a3332853345e32" ON "posts" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_a56e2db14676f90be1694e2723" ON "posts" ("parent_txid") `)
        await queryRunner.query(`CREATE INDEX "IDX_565d3e71ac2ea22a54a0631994" ON "posts" ("sender_address") `)
        await queryRunner.query(`DROP INDEX "IDX_4149b5d28a9d574cb35ac0b880"`)
        await queryRunner.query(`DROP INDEX "IDX_08f49bf2cacd532e2e10eb5779"`)
        await queryRunner.query(`DROP INDEX "IDX_2ccda451e12bc68c5af8d3c9b4"`)
        await queryRunner.query(`DROP INDEX "IDX_17be0dbba5ea05d3c431737ba8"`)
        await queryRunner.query(`DROP INDEX "IDX_617a3a43a298c164330279390c"`)
        await queryRunner.query(`DROP INDEX "IDX_1d57610e4bf65bca7df9f747be"`)
        await queryRunner.query(`DROP INDEX "IDX_d8dc419b6ee03babf580a7b3c3"`)
        await queryRunner.query(`CREATE TABLE "temporary_orphans" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "block_height" bigint NOT NULL, "nonce" integer, "position" integer, "type" text NOT NULL, "content" text, "reference_id" text, "reference_sender_address" text, "mentions" text, "sender_address" text, CONSTRAINT "FK_d8dc419b6ee03babf580a7b3c30" FOREIGN KEY ("sender_address") REFERENCES "users" ("address"))`)
        await queryRunner.query(`INSERT INTO "temporary_orphans"("txid", "created_at", "block_height", "nonce", "position", "type", "content", "reference_id", "reference_sender_address", "mentions", "sender_address") SELECT "txid", "created_at", "block_height", "nonce", "position", "type", "content", "reference_id", "reference_sender_address", "mentions", "sender_address" FROM "orphans"`)
        await queryRunner.query(`DROP TABLE "orphans"`)
        await queryRunner.query(`ALTER TABLE "temporary_orphans" RENAME TO "orphans"`)
        await queryRunner.query(`CREATE INDEX "IDX_4149b5d28a9d574cb35ac0b880" ON "orphans" ("created_at") `)
        await queryRunner.query(`CREATE INDEX "IDX_08f49bf2cacd532e2e10eb5779" ON "orphans" ("block_height") `)
        await queryRunner.query(`CREATE INDEX "IDX_2ccda451e12bc68c5af8d3c9b4" ON "orphans" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_17be0dbba5ea05d3c431737ba8" ON "orphans" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_617a3a43a298c164330279390c" ON "orphans" ("reference_id") `)
        await queryRunner.query(`CREATE INDEX "IDX_1d57610e4bf65bca7df9f747be" ON "orphans" ("reference_sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_d8dc419b6ee03babf580a7b3c3" ON "orphans" ("sender_address") `)
        await queryRunner.query(`CREATE TABLE "temporary_post_tags" ("tag_name" text NOT NULL, "post_txid" text NOT NULL, CONSTRAINT "FK_400e719fd738123e7bcdae675a3" FOREIGN KEY ("tag_name") REFERENCES "tags" ("name") ON DELETE CASCADE, CONSTRAINT "FK_2b73ad3de85484c053b3ffa0438" FOREIGN KEY ("post_txid") REFERENCES "posts" ("txid") ON DELETE CASCADE, PRIMARY KEY ("tag_name", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "temporary_post_tags"("tag_name", "post_txid") SELECT "tag_name", "post_txid" FROM "post_tags"`)
        await queryRunner.query(`DROP TABLE "post_tags"`)
        await queryRunner.query(`ALTER TABLE "temporary_post_tags" RENAME TO "post_tags"`)
        await queryRunner.query(`CREATE TABLE "temporary_follows" ("followed_address" text NOT NULL, "follower_address" text NOT NULL, CONSTRAINT "FK_896ecc3e22c5f3b9fe89e5f6699" FOREIGN KEY ("followed_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_735aa5a2ac167c99c74ee24650e" FOREIGN KEY ("follower_address") REFERENCES "users" ("address") ON DELETE CASCADE, PRIMARY KEY ("followed_address", "follower_address"))`)
        await queryRunner.query(`INSERT INTO "temporary_follows"("followed_address", "follower_address") SELECT "followed_address", "follower_address" FROM "follows"`)
        await queryRunner.query(`DROP TABLE "follows"`)
        await queryRunner.query(`ALTER TABLE "temporary_follows" RENAME TO "follows"`)
        await queryRunner.query(`CREATE TABLE "temporary_blocks" ("blocked_address" text NOT NULL, "blocker_address" text NOT NULL, CONSTRAINT "FK_ecba0d996258678e9780ed88b70" FOREIGN KEY ("blocked_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_de6aa57933625d2ce35c1650908" FOREIGN KEY ("blocker_address") REFERENCES "users" ("address") ON DELETE CASCADE, PRIMARY KEY ("blocked_address", "blocker_address"))`)
        await queryRunner.query(`INSERT INTO "temporary_blocks"("blocked_address", "blocker_address") SELECT "blocked_address", "blocker_address" FROM "blocks"`)
        await queryRunner.query(`DROP TABLE "blocks"`)
        await queryRunner.query(`ALTER TABLE "temporary_blocks" RENAME TO "blocks"`)
        await queryRunner.query(`CREATE TABLE "temporary_likes" ("user_address" text NOT NULL, "post_txid" text NOT NULL, CONSTRAINT "FK_9b4c20f1f1493294a764604d8ac" FOREIGN KEY ("user_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_b25aa0858fd2021998e5e454324" FOREIGN KEY ("post_txid") REFERENCES "posts" ("txid") ON DELETE CASCADE, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "temporary_likes"("user_address", "post_txid") SELECT "user_address", "post_txid" FROM "likes"`)
        await queryRunner.query(`DROP TABLE "likes"`)
        await queryRunner.query(`ALTER TABLE "temporary_likes" RENAME TO "likes"`)
        await queryRunner.query(`CREATE TABLE "temporary_flags" ("user_address" text NOT NULL, "post_txid" text NOT NULL, CONSTRAINT "FK_77d950f40f013776b34106746f9" FOREIGN KEY ("user_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_d330f48942ea78a2a9df64c9965" FOREIGN KEY ("post_txid") REFERENCES "posts" ("txid") ON DELETE CASCADE, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "temporary_flags"("user_address", "post_txid") SELECT "user_address", "post_txid" FROM "flags"`)
        await queryRunner.query(`DROP TABLE "flags"`)
        await queryRunner.query(`ALTER TABLE "temporary_flags" RENAME TO "flags"`)
        await queryRunner.query(`CREATE TABLE "temporary_mentions" ("user_address" text NOT NULL, "post_txid" text NOT NULL, CONSTRAINT "FK_73bf803442939c9f00e57958b3f" FOREIGN KEY ("user_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_f9278f3ddb4563dc57047a16fdd" FOREIGN KEY ("post_txid") REFERENCES "posts" ("txid") ON DELETE CASCADE, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "temporary_mentions"("user_address", "post_txid") SELECT "user_address", "post_txid" FROM "mentions"`)
        await queryRunner.query(`DROP TABLE "mentions"`)
        await queryRunner.query(`ALTER TABLE "temporary_mentions" RENAME TO "mentions"`)
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "mentions" RENAME TO "temporary_mentions"`)
        await queryRunner.query(`CREATE TABLE "mentions" ("user_address" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "mentions"("user_address", "post_txid") SELECT "user_address", "post_txid" FROM "temporary_mentions"`)
        await queryRunner.query(`DROP TABLE "temporary_mentions"`)
        await queryRunner.query(`ALTER TABLE "flags" RENAME TO "temporary_flags"`)
        await queryRunner.query(`CREATE TABLE "flags" ("user_address" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "flags"("user_address", "post_txid") SELECT "user_address", "post_txid" FROM "temporary_flags"`)
        await queryRunner.query(`DROP TABLE "temporary_flags"`)
        await queryRunner.query(`ALTER TABLE "likes" RENAME TO "temporary_likes"`)
        await queryRunner.query(`CREATE TABLE "likes" ("user_address" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "likes"("user_address", "post_txid") SELECT "user_address", "post_txid" FROM "temporary_likes"`)
        await queryRunner.query(`DROP TABLE "temporary_likes"`)
        await queryRunner.query(`ALTER TABLE "blocks" RENAME TO "temporary_blocks"`)
        await queryRunner.query(`CREATE TABLE "blocks" ("blocked_address" text NOT NULL, "blocker_address" text NOT NULL, PRIMARY KEY ("blocked_address", "blocker_address"))`)
        await queryRunner.query(`INSERT INTO "blocks"("blocked_address", "blocker_address") SELECT "blocked_address", "blocker_address" FROM "temporary_blocks"`)
        await queryRunner.query(`DROP TABLE "temporary_blocks"`)
        await queryRunner.query(`ALTER TABLE "follows" RENAME TO "temporary_follows"`)
        await queryRunner.query(`CREATE TABLE "follows" ("followed_address" text NOT NULL, "follower_address" text NOT NULL, PRIMARY KEY ("followed_address", "follower_address"))`)
        await queryRunner.query(`INSERT INTO "follows"("followed_address", "follower_address") SELECT "followed_address", "follower_address" FROM "temporary_follows"`)
        await queryRunner.query(`DROP TABLE "temporary_follows"`)
        await queryRunner.query(`ALTER TABLE "post_tags" RENAME TO "temporary_post_tags"`)
        await queryRunner.query(`CREATE TABLE "post_tags" ("tag_name" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("tag_name", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "post_tags"("tag_name", "post_txid") SELECT "tag_name", "post_txid" FROM "temporary_post_tags"`)
        await queryRunner.query(`DROP TABLE "temporary_post_tags"`)
        await queryRunner.query(`DROP INDEX "IDX_d8dc419b6ee03babf580a7b3c3"`)
        await queryRunner.query(`DROP INDEX "IDX_1d57610e4bf65bca7df9f747be"`)
        await queryRunner.query(`DROP INDEX "IDX_617a3a43a298c164330279390c"`)
        await queryRunner.query(`DROP INDEX "IDX_17be0dbba5ea05d3c431737ba8"`)
        await queryRunner.query(`DROP INDEX "IDX_2ccda451e12bc68c5af8d3c9b4"`)
        await queryRunner.query(`DROP INDEX "IDX_08f49bf2cacd532e2e10eb5779"`)
        await queryRunner.query(`DROP INDEX "IDX_4149b5d28a9d574cb35ac0b880"`)
        await queryRunner.query(`ALTER TABLE "orphans" RENAME TO "temporary_orphans"`)
        await queryRunner.query(`CREATE TABLE "orphans" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "block_height" bigint NOT NULL, "nonce" integer, "position" integer, "type" text NOT NULL, "content" text, "reference_id" text, "reference_sender_address" text, "mentions" text, "sender_address" text)`)
        await queryRunner.query(`INSERT INTO "orphans"("txid", "created_at", "block_height", "nonce", "position", "type", "content", "reference_id", "reference_sender_address", "mentions", "sender_address") SELECT "txid", "created_at", "block_height", "nonce", "position", "type", "content", "reference_id", "reference_sender_address", "mentions", "sender_address" FROM "temporary_orphans"`)
        await queryRunner.query(`DROP TABLE "temporary_orphans"`)
        await queryRunner.query(`CREATE INDEX "IDX_d8dc419b6ee03babf580a7b3c3" ON "orphans" ("sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_1d57610e4bf65bca7df9f747be" ON "orphans" ("reference_sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_617a3a43a298c164330279390c" ON "orphans" ("reference_id") `)
        await queryRunner.query(`CREATE INDEX "IDX_17be0dbba5ea05d3c431737ba8" ON "orphans" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_2ccda451e12bc68c5af8d3c9b4" ON "orphans" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_08f49bf2cacd532e2e10eb5779" ON "orphans" ("block_height") `)
        await queryRunner.query(`CREATE INDEX "IDX_4149b5d28a9d574cb35ac0b880" ON "orphans" ("created_at") `)
        await queryRunner.query(`DROP INDEX "IDX_565d3e71ac2ea22a54a0631994"`)
        await queryRunner.query(`DROP INDEX "IDX_a56e2db14676f90be1694e2723"`)
        await queryRunner.query(`DROP INDEX "IDX_560752d45d78a3332853345e32"`)
        await queryRunner.query(`DROP INDEX "IDX_862deee3599ab1a65f8d6a4845"`)
        await queryRunner.query(`DROP INDEX "IDX_60818528127866f5002e7f826d"`)
        await queryRunner.query(`ALTER TABLE "posts" RENAME TO "temporary_posts"`)
        await queryRunner.query(`CREATE TABLE "posts" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "deleted_at" datetime, "nonce" integer NOT NULL, "position" integer NOT NULL, "type" text NOT NULL, "content" text, "parent_txid" text, "sender_address" text)`)
        await queryRunner.query(`INSERT INTO "posts"("txid", "created_at", "deleted_at", "nonce", "position", "type", "content", "parent_txid", "sender_address") SELECT "txid", "created_at", "deleted_at", "nonce", "position", "type", "content", "parent_txid", "sender_address" FROM "temporary_posts"`)
        await queryRunner.query(`DROP TABLE "temporary_posts"`)
        await queryRunner.query(`CREATE INDEX "IDX_565d3e71ac2ea22a54a0631994" ON "posts" ("sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_a56e2db14676f90be1694e2723" ON "posts" ("parent_txid") `)
        await queryRunner.query(`CREATE INDEX "IDX_560752d45d78a3332853345e32" ON "posts" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_862deee3599ab1a65f8d6a4845" ON "posts" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_60818528127866f5002e7f826d" ON "posts" ("created_at") `)
        await queryRunner.query(`DROP TABLE "mentions"`)
        await queryRunner.query(`DROP TABLE "flags"`)
        await queryRunner.query(`DROP TABLE "likes"`)
        await queryRunner.query(`DROP TABLE "blocks"`)
        await queryRunner.query(`DROP TABLE "follows"`)
        await queryRunner.query(`DROP TABLE "post_tags"`)
        await queryRunner.query(`DROP INDEX "IDX_7ee003620e5c4dc41c8020c3a4"`)
        await queryRunner.query(`DROP INDEX "IDX_f4ddf5596761915d4415c18040"`)
        await queryRunner.query(`DROP TABLE "utxos"`)
        await queryRunner.query(`DROP INDEX "IDX_d16046b3c22e0ac37b9367ba8d"`)
        await queryRunner.query(`DROP TABLE "tx_blocks"`)
        await queryRunner.query(`DROP INDEX "IDX_d8dc419b6ee03babf580a7b3c3"`)
        await queryRunner.query(`DROP INDEX "IDX_1d57610e4bf65bca7df9f747be"`)
        await queryRunner.query(`DROP INDEX "IDX_617a3a43a298c164330279390c"`)
        await queryRunner.query(`DROP INDEX "IDX_17be0dbba5ea05d3c431737ba8"`)
        await queryRunner.query(`DROP INDEX "IDX_2ccda451e12bc68c5af8d3c9b4"`)
        await queryRunner.query(`DROP INDEX "IDX_08f49bf2cacd532e2e10eb5779"`)
        await queryRunner.query(`DROP INDEX "IDX_4149b5d28a9d574cb35ac0b880"`)
        await queryRunner.query(`DROP TABLE "orphans"`)
        await queryRunner.query(`DROP INDEX "IDX_1b4832240d11291453c40c3281"`)
        await queryRunner.query(`DROP TABLE "users"`)
        await queryRunner.query(`DROP INDEX "IDX_565d3e71ac2ea22a54a0631994"`)
        await queryRunner.query(`DROP INDEX "IDX_a56e2db14676f90be1694e2723"`)
        await queryRunner.query(`DROP INDEX "IDX_560752d45d78a3332853345e32"`)
        await queryRunner.query(`DROP INDEX "IDX_862deee3599ab1a65f8d6a4845"`)
        await queryRunner.query(`DROP INDEX "IDX_60818528127866f5002e7f826d"`)
        await queryRunner.query(`DROP TABLE "posts"`)
        await queryRunner.query(`DROP TABLE "tags"`)
    }

}
