import { MigrationInterface, QueryRunner } from 'typeorm'

export class Init1559007225950 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "tags" ("name" text PRIMARY KEY NOT NULL)`)
        await queryRunner.query(`CREATE TABLE "posts" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "deleted_at" datetime, "nonce" integer NOT NULL, "index" integer NOT NULL, "type" text NOT NULL, "content" text, "parent_txid" text, "sender_address" text)`)
        await queryRunner.query(`CREATE INDEX "IDX_60818528127866f5002e7f826d" ON "posts" ("created_at") `)
        await queryRunner.query(`CREATE INDEX "IDX_30529cebbe83139b966d29a2b6" ON "posts" ("index") `)
        await queryRunner.query(`CREATE INDEX "IDX_560752d45d78a3332853345e32" ON "posts" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_a56e2db14676f90be1694e2723" ON "posts" ("parent_txid") `)
        await queryRunner.query(`CREATE INDEX "IDX_565d3e71ac2ea22a54a0631994" ON "posts" ("sender_address") `)
        await queryRunner.query(`CREATE TABLE "users" ("address" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "birth_block" integer NOT NULL, "name" text NOT NULL, "bio" text, "avatar_link" text)`)
        await queryRunner.query(`CREATE INDEX "IDX_1b4832240d11291453c40c3281" ON "users" ("birth_block") `)
        await queryRunner.query(`CREATE TABLE "orphans_cr" ("created_at" datetime NOT NULL, "reference_id" text NOT NULL, "post_txid" text PRIMARY KEY NOT NULL, "parent_sender_address" text, CONSTRAINT "REL_453e8bd4503f44bd0aedac4a45" UNIQUE ("post_txid"))`)
        await queryRunner.query(`CREATE INDEX "IDX_fbace1dc23c4d3e28315d8d5ec" ON "orphans_cr" ("reference_id") `)
        await queryRunner.query(`CREATE INDEX "IDX_c777511036debb82d9676b6d02" ON "orphans_cr" ("parent_sender_address") `)
        await queryRunner.query(`CREATE TABLE "utxos" ("txid" text NOT NULL, "index" integer NOT NULL, "address" text NOT NULL, "value" bigint NOT NULL, "raw" text NOT NULL, PRIMARY KEY ("txid", "index"))`)
        await queryRunner.query(`CREATE INDEX "IDX_7ee003620e5c4dc41c8020c3a4" ON "utxos" ("address") `)
        await queryRunner.query(`CREATE TABLE "post_tags" ("tag_name" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("tag_name", "post_txid"))`)
        await queryRunner.query(`CREATE TABLE "follows" ("followed_address" text NOT NULL, "follower_address" text NOT NULL, PRIMARY KEY ("followed_address", "follower_address"))`)
        await queryRunner.query(`CREATE TABLE "blocks" ("blocked_address" text NOT NULL, "blocker_address" text NOT NULL, PRIMARY KEY ("blocked_address", "blocker_address"))`)
        await queryRunner.query(`CREATE TABLE "likes" ("user_address" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`CREATE TABLE "flags" ("user_address" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`CREATE TABLE "mentions" ("user_address" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`DROP INDEX "IDX_60818528127866f5002e7f826d"`)
        await queryRunner.query(`DROP INDEX "IDX_30529cebbe83139b966d29a2b6"`)
        await queryRunner.query(`DROP INDEX "IDX_560752d45d78a3332853345e32"`)
        await queryRunner.query(`DROP INDEX "IDX_a56e2db14676f90be1694e2723"`)
        await queryRunner.query(`DROP INDEX "IDX_565d3e71ac2ea22a54a0631994"`)
        await queryRunner.query(`CREATE TABLE "temporary_posts" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "deleted_at" datetime, "nonce" integer NOT NULL, "index" integer NOT NULL, "type" text NOT NULL, "content" text, "parent_txid" text, "sender_address" text, CONSTRAINT "FK_a56e2db14676f90be1694e27235" FOREIGN KEY ("parent_txid") REFERENCES "posts" ("txid"), CONSTRAINT "FK_565d3e71ac2ea22a54a0631994b" FOREIGN KEY ("sender_address") REFERENCES "users" ("address"))`)
        await queryRunner.query(`INSERT INTO "temporary_posts"("txid", "created_at", "deleted_at", "nonce", "index", "type", "content", "parent_txid", "sender_address") SELECT "txid", "created_at", "deleted_at", "nonce", "index", "type", "content", "parent_txid", "sender_address" FROM "posts"`)
        await queryRunner.query(`DROP TABLE "posts"`)
        await queryRunner.query(`ALTER TABLE "temporary_posts" RENAME TO "posts"`)
        await queryRunner.query(`CREATE INDEX "IDX_60818528127866f5002e7f826d" ON "posts" ("created_at") `)
        await queryRunner.query(`CREATE INDEX "IDX_30529cebbe83139b966d29a2b6" ON "posts" ("index") `)
        await queryRunner.query(`CREATE INDEX "IDX_560752d45d78a3332853345e32" ON "posts" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_a56e2db14676f90be1694e2723" ON "posts" ("parent_txid") `)
        await queryRunner.query(`CREATE INDEX "IDX_565d3e71ac2ea22a54a0631994" ON "posts" ("sender_address") `)
        await queryRunner.query(`DROP INDEX "IDX_fbace1dc23c4d3e28315d8d5ec"`)
        await queryRunner.query(`DROP INDEX "IDX_c777511036debb82d9676b6d02"`)
        await queryRunner.query(`CREATE TABLE "temporary_orphans_cr" ("created_at" datetime NOT NULL, "reference_id" text NOT NULL, "post_txid" text PRIMARY KEY NOT NULL, "parent_sender_address" text, CONSTRAINT "REL_453e8bd4503f44bd0aedac4a45" UNIQUE ("post_txid"), CONSTRAINT "FK_453e8bd4503f44bd0aedac4a452" FOREIGN KEY ("post_txid") REFERENCES "posts" ("txid"), CONSTRAINT "FK_c777511036debb82d9676b6d02f" FOREIGN KEY ("parent_sender_address") REFERENCES "users" ("address"))`)
        await queryRunner.query(`INSERT INTO "temporary_orphans_cr"("created_at", "reference_id", "post_txid", "parent_sender_address") SELECT "created_at", "reference_id", "post_txid", "parent_sender_address" FROM "orphans_cr"`)
        await queryRunner.query(`DROP TABLE "orphans_cr"`)
        await queryRunner.query(`ALTER TABLE "temporary_orphans_cr" RENAME TO "orphans_cr"`)
        await queryRunner.query(`CREATE INDEX "IDX_fbace1dc23c4d3e28315d8d5ec" ON "orphans_cr" ("reference_id") `)
        await queryRunner.query(`CREATE INDEX "IDX_c777511036debb82d9676b6d02" ON "orphans_cr" ("parent_sender_address") `)
        await queryRunner.query(`CREATE TABLE "temporary_post_tags" ("tag_name" text NOT NULL, "post_txid" text NOT NULL, CONSTRAINT "FK_400e719fd738123e7bcdae675a3" FOREIGN KEY ("tag_name") REFERENCES "tags" ("name") ON DELETE CASCADE, CONSTRAINT "FK_2b73ad3de85484c053b3ffa0438" FOREIGN KEY ("post_txid") REFERENCES "posts" ("txid") ON DELETE CASCADE, PRIMARY KEY ("tag_name", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "temporary_post_tags"("tag_name", "post_txid") SELECT "tag_name", "post_txid" FROM "post_tags"`)
        await queryRunner.query(`DROP TABLE "post_tags"`)
        await queryRunner.query(`ALTER TABLE "temporary_post_tags" RENAME TO "post_tags"`)
        await queryRunner.query(`CREATE TABLE "temporary_follows" ("followed_address" text NOT NULL, "follower_address" text NOT NULL, CONSTRAINT "FK_896ecc3e22c5f3b9fe89e5f6699" FOREIGN KEY ("followed_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_735aa5a2ac167c99c74ee24650e" FOREIGN KEY ("follower_address") REFERENCES "users" ("address") ON DELETE CASCADE, PRIMARY KEY ("followed_address", "follower_address"))`)
        await queryRunner.query(`INSERT INTO "temporary_follows"("followed_address", "follower_address") SELECT "followed_address", "follower_address" FROM "follows"`)
        await queryRunner.query(`DROP TABLE "follows"`)
        await queryRunner.query(`ALTER TABLE "temporary_follows" RENAME TO "follows"`)
        await queryRunner.query(`CREATE TABLE "temporary_blocks" ("blocked_address" text NOT NULL, "blocker_address" text NOT NULL, CONSTRAINT "FK_ecba0d996258678e9780ed88b70" FOREIGN KEY ("blocked_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_de6aa57933625d2ce35c1650908" FOREIGN KEY ("blocker_address") REFERENCES "users" ("address") ON DELETE CASCADE, PRIMARY KEY ("blocked_address", "blocker_address"))`)
        await queryRunner.query(`INSERT INTO "temporary_blocks"("blocked_address", "blocker_address") SELECT "blocked_address", "blocker_address" FROM "blocks"`)
        await queryRunner.query(`DROP TABLE "blocks"`)
        await queryRunner.query(`ALTER TABLE "temporary_blocks" RENAME TO "blocks"`)
        await queryRunner.query(`CREATE TABLE "temporary_likes" ("user_address" text NOT NULL, "post_txid" text NOT NULL, CONSTRAINT "FK_9b4c20f1f1493294a764604d8ac" FOREIGN KEY ("user_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_b25aa0858fd2021998e5e454324" FOREIGN KEY ("post_txid") REFERENCES "posts" ("txid") ON DELETE CASCADE, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "temporary_likes"("user_address", "post_txid") SELECT "user_address", "post_txid" FROM "likes"`)
        await queryRunner.query(`DROP TABLE "likes"`)
        await queryRunner.query(`ALTER TABLE "temporary_likes" RENAME TO "likes"`)
        await queryRunner.query(`CREATE TABLE "temporary_flags" ("user_address" text NOT NULL, "post_txid" text NOT NULL, CONSTRAINT "FK_77d950f40f013776b34106746f9" FOREIGN KEY ("user_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_d330f48942ea78a2a9df64c9965" FOREIGN KEY ("post_txid") REFERENCES "posts" ("txid") ON DELETE CASCADE, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "temporary_flags"("user_address", "post_txid") SELECT "user_address", "post_txid" FROM "flags"`)
        await queryRunner.query(`DROP TABLE "flags"`)
        await queryRunner.query(`ALTER TABLE "temporary_flags" RENAME TO "flags"`)
        await queryRunner.query(`CREATE TABLE "temporary_mentions" ("user_address" text NOT NULL, "post_txid" text NOT NULL, CONSTRAINT "FK_73bf803442939c9f00e57958b3f" FOREIGN KEY ("user_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_f9278f3ddb4563dc57047a16fdd" FOREIGN KEY ("post_txid") REFERENCES "posts" ("txid") ON DELETE CASCADE, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "temporary_mentions"("user_address", "post_txid") SELECT "user_address", "post_txid" FROM "mentions"`)
        await queryRunner.query(`DROP TABLE "mentions"`)
        await queryRunner.query(`ALTER TABLE "temporary_mentions" RENAME TO "mentions"`)
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "mentions" RENAME TO "temporary_mentions"`)
        await queryRunner.query(`CREATE TABLE "mentions" ("user_address" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "mentions"("user_address", "post_txid") SELECT "user_address", "post_txid" FROM "temporary_mentions"`)
        await queryRunner.query(`DROP TABLE "temporary_mentions"`)
        await queryRunner.query(`ALTER TABLE "flags" RENAME TO "temporary_flags"`)
        await queryRunner.query(`CREATE TABLE "flags" ("user_address" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "flags"("user_address", "post_txid") SELECT "user_address", "post_txid" FROM "temporary_flags"`)
        await queryRunner.query(`DROP TABLE "temporary_flags"`)
        await queryRunner.query(`ALTER TABLE "likes" RENAME TO "temporary_likes"`)
        await queryRunner.query(`CREATE TABLE "likes" ("user_address" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("user_address", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "likes"("user_address", "post_txid") SELECT "user_address", "post_txid" FROM "temporary_likes"`)
        await queryRunner.query(`DROP TABLE "temporary_likes"`)
        await queryRunner.query(`ALTER TABLE "blocks" RENAME TO "temporary_blocks"`)
        await queryRunner.query(`CREATE TABLE "blocks" ("blocked_address" text NOT NULL, "blocker_address" text NOT NULL, PRIMARY KEY ("blocked_address", "blocker_address"))`)
        await queryRunner.query(`INSERT INTO "blocks"("blocked_address", "blocker_address") SELECT "blocked_address", "blocker_address" FROM "temporary_blocks"`)
        await queryRunner.query(`DROP TABLE "temporary_blocks"`)
        await queryRunner.query(`ALTER TABLE "follows" RENAME TO "temporary_follows"`)
        await queryRunner.query(`CREATE TABLE "follows" ("followed_address" text NOT NULL, "follower_address" text NOT NULL, PRIMARY KEY ("followed_address", "follower_address"))`)
        await queryRunner.query(`INSERT INTO "follows"("followed_address", "follower_address") SELECT "followed_address", "follower_address" FROM "temporary_follows"`)
        await queryRunner.query(`DROP TABLE "temporary_follows"`)
        await queryRunner.query(`ALTER TABLE "post_tags" RENAME TO "temporary_post_tags"`)
        await queryRunner.query(`CREATE TABLE "post_tags" ("tag_name" text NOT NULL, "post_txid" text NOT NULL, PRIMARY KEY ("tag_name", "post_txid"))`)
        await queryRunner.query(`INSERT INTO "post_tags"("tag_name", "post_txid") SELECT "tag_name", "post_txid" FROM "temporary_post_tags"`)
        await queryRunner.query(`DROP TABLE "temporary_post_tags"`)
        await queryRunner.query(`DROP INDEX "IDX_c777511036debb82d9676b6d02"`)
        await queryRunner.query(`DROP INDEX "IDX_fbace1dc23c4d3e28315d8d5ec"`)
        await queryRunner.query(`ALTER TABLE "orphans_cr" RENAME TO "temporary_orphans_cr"`)
        await queryRunner.query(`CREATE TABLE "orphans_cr" ("created_at" datetime NOT NULL, "reference_id" text NOT NULL, "post_txid" text PRIMARY KEY NOT NULL, "parent_sender_address" text, CONSTRAINT "REL_453e8bd4503f44bd0aedac4a45" UNIQUE ("post_txid"))`)
        await queryRunner.query(`INSERT INTO "orphans_cr"("created_at", "reference_id", "post_txid", "parent_sender_address") SELECT "created_at", "reference_id", "post_txid", "parent_sender_address" FROM "temporary_orphans_cr"`)
        await queryRunner.query(`DROP TABLE "temporary_orphans_cr"`)
        await queryRunner.query(`CREATE INDEX "IDX_c777511036debb82d9676b6d02" ON "orphans_cr" ("parent_sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_fbace1dc23c4d3e28315d8d5ec" ON "orphans_cr" ("reference_id") `)
        await queryRunner.query(`DROP INDEX "IDX_565d3e71ac2ea22a54a0631994"`)
        await queryRunner.query(`DROP INDEX "IDX_a56e2db14676f90be1694e2723"`)
        await queryRunner.query(`DROP INDEX "IDX_560752d45d78a3332853345e32"`)
        await queryRunner.query(`DROP INDEX "IDX_30529cebbe83139b966d29a2b6"`)
        await queryRunner.query(`DROP INDEX "IDX_60818528127866f5002e7f826d"`)
        await queryRunner.query(`ALTER TABLE "posts" RENAME TO "temporary_posts"`)
        await queryRunner.query(`CREATE TABLE "posts" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "deleted_at" datetime, "nonce" integer NOT NULL, "index" integer NOT NULL, "type" text NOT NULL, "content" text, "parent_txid" text, "sender_address" text)`)
        await queryRunner.query(`INSERT INTO "posts"("txid", "created_at", "deleted_at", "nonce", "index", "type", "content", "parent_txid", "sender_address") SELECT "txid", "created_at", "deleted_at", "nonce", "index", "type", "content", "parent_txid", "sender_address" FROM "temporary_posts"`)
        await queryRunner.query(`DROP TABLE "temporary_posts"`)
        await queryRunner.query(`CREATE INDEX "IDX_565d3e71ac2ea22a54a0631994" ON "posts" ("sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_a56e2db14676f90be1694e2723" ON "posts" ("parent_txid") `)
        await queryRunner.query(`CREATE INDEX "IDX_560752d45d78a3332853345e32" ON "posts" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_30529cebbe83139b966d29a2b6" ON "posts" ("index") `)
        await queryRunner.query(`CREATE INDEX "IDX_60818528127866f5002e7f826d" ON "posts" ("created_at") `)
        await queryRunner.query(`DROP TABLE "mentions"`)
        await queryRunner.query(`DROP TABLE "flags"`)
        await queryRunner.query(`DROP TABLE "likes"`)
        await queryRunner.query(`DROP TABLE "blocks"`)
        await queryRunner.query(`DROP TABLE "follows"`)
        await queryRunner.query(`DROP TABLE "post_tags"`)
        await queryRunner.query(`DROP INDEX "IDX_7ee003620e5c4dc41c8020c3a4"`)
        await queryRunner.query(`DROP TABLE "utxos"`)
        await queryRunner.query(`DROP INDEX "IDX_c777511036debb82d9676b6d02"`)
        await queryRunner.query(`DROP INDEX "IDX_fbace1dc23c4d3e28315d8d5ec"`)
        await queryRunner.query(`DROP TABLE "orphans_cr"`)
        await queryRunner.query(`DROP INDEX "IDX_1b4832240d11291453c40c3281"`)
        await queryRunner.query(`DROP TABLE "users"`)
        await queryRunner.query(`DROP INDEX "IDX_565d3e71ac2ea22a54a0631994"`)
        await queryRunner.query(`DROP INDEX "IDX_a56e2db14676f90be1694e2723"`)
        await queryRunner.query(`DROP INDEX "IDX_560752d45d78a3332853345e32"`)
        await queryRunner.query(`DROP INDEX "IDX_30529cebbe83139b966d29a2b6"`)
        await queryRunner.query(`DROP INDEX "IDX_60818528127866f5002e7f826d"`)
        await queryRunner.query(`DROP TABLE "posts"`)
        await queryRunner.query(`DROP TABLE "tags"`)
    }

}
