import { MigrationInterface, QueryRunner } from 'typeorm'

export class Init1559505099123 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "likes" ("post_txid" text NOT NULL, "user_address" text NOT NULL, "block_height" bigint NOT NULL, PRIMARY KEY ("post_txid", "user_address", "block_height"))`)
        await queryRunner.query(`CREATE TABLE "user_blocks" ("blocker_address" text NOT NULL, "blocked_address" text NOT NULL, "block_height" bigint NOT NULL, PRIMARY KEY ("blocker_address", "blocked_address", "block_height"))`)
        await queryRunner.query(`CREATE TABLE "follows" ("followed_address" text NOT NULL, "following_address" text NOT NULL, "block_height" bigint NOT NULL, PRIMARY KEY ("followed_address", "following_address", "block_height"))`)
        await queryRunner.query(`CREATE TABLE "flags" ("post_txid" text NOT NULL, "user_address" text NOT NULL, "block_height" bigint NOT NULL, PRIMARY KEY ("post_txid", "user_address", "block_height"))`)
        await queryRunner.query(`CREATE TABLE "mentions" ("post_txid" text NOT NULL, "user_address" text NOT NULL, "block_height" bigint NOT NULL, PRIMARY KEY ("post_txid", "user_address", "block_height"))`)
        await queryRunner.query(`CREATE TABLE "orphans" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "nonce" integer, "position" integer, "type" text NOT NULL, "content" text, "reference_id" text, "reference_sender_address" text, "mentions" text, "sender_address" text, "block_height" bigint)`)
        await queryRunner.query(`CREATE INDEX "IDX_4149b5d28a9d574cb35ac0b880" ON "orphans" ("created_at") `)
        await queryRunner.query(`CREATE INDEX "IDX_2ccda451e12bc68c5af8d3c9b4" ON "orphans" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_17be0dbba5ea05d3c431737ba8" ON "orphans" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_617a3a43a298c164330279390c" ON "orphans" ("reference_id") `)
        await queryRunner.query(`CREATE INDEX "IDX_1d57610e4bf65bca7df9f747be" ON "orphans" ("reference_sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_d8dc419b6ee03babf580a7b3c3" ON "orphans" ("sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_08f49bf2cacd532e2e10eb5779" ON "orphans" ("block_height") `)
        await queryRunner.query(`CREATE TABLE "users" ("address" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "name" text NOT NULL, "bio" text, "avatar_link" text, "block_height" bigint)`)
        await queryRunner.query(`CREATE INDEX "IDX_44ae61e72134027b2cc37050bd" ON "users" ("block_height") `)
        await queryRunner.query(`CREATE TABLE "tags" ("name" text PRIMARY KEY NOT NULL, "block_height" bigint)`)
        await queryRunner.query(`CREATE INDEX "IDX_8a2798743aa93a0242df71ceed" ON "tags" ("block_height") `)
        await queryRunner.query(`CREATE TABLE "post_tags" ("post_txid" text NOT NULL, "tag_name" text NOT NULL, "block_height" bigint NOT NULL, PRIMARY KEY ("post_txid", "tag_name", "block_height"))`)
        await queryRunner.query(`CREATE TABLE "posts" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "deleted_at" datetime, "nonce" integer NOT NULL, "position" integer NOT NULL, "type" text NOT NULL, "content" text, "block_height" bigint, "parent_txid" text, "sender_address" text)`)
        await queryRunner.query(`CREATE INDEX "IDX_60818528127866f5002e7f826d" ON "posts" ("created_at") `)
        await queryRunner.query(`CREATE INDEX "IDX_862deee3599ab1a65f8d6a4845" ON "posts" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_560752d45d78a3332853345e32" ON "posts" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_5e9b13dbe0048d25c4b87d5b67" ON "posts" ("block_height") `)
        await queryRunner.query(`CREATE INDEX "IDX_a56e2db14676f90be1694e2723" ON "posts" ("parent_txid") `)
        await queryRunner.query(`CREATE INDEX "IDX_565d3e71ac2ea22a54a0631994" ON "posts" ("sender_address") `)
        await queryRunner.query(`CREATE TABLE "utxos" ("txid" text NOT NULL, "position" integer NOT NULL, "address" text NOT NULL, "value" bigint NOT NULL, "raw" text NOT NULL, "block_height" bigint, PRIMARY KEY ("txid", "position"))`)
        await queryRunner.query(`CREATE INDEX "IDX_7ee003620e5c4dc41c8020c3a4" ON "utxos" ("address") `)
        await queryRunner.query(`CREATE INDEX "IDX_f4ddf5596761915d4415c18040" ON "utxos" ("block_height") `)
        await queryRunner.query(`CREATE TABLE "blocks" ("height" bigint PRIMARY KEY NOT NULL, "hash" text NOT NULL, CONSTRAINT "UQ_00d4f3eb491f00ae5bece2a559e" UNIQUE ("hash"))`)
        await queryRunner.query(`CREATE INDEX "IDX_00d4f3eb491f00ae5bece2a559" ON "blocks" ("hash") `)
        await queryRunner.query(`CREATE TABLE "temporary_likes" ("post_txid" text NOT NULL, "user_address" text NOT NULL, "block_height" bigint NOT NULL, CONSTRAINT "FK_b25aa0858fd2021998e5e454324" FOREIGN KEY ("post_txid") REFERENCES "posts" ("txid") ON DELETE CASCADE, CONSTRAINT "FK_9b4c20f1f1493294a764604d8ac" FOREIGN KEY ("user_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_77c035c3922317074efd0303304" FOREIGN KEY ("block_height") REFERENCES "blocks" ("height") ON DELETE CASCADE, PRIMARY KEY ("post_txid", "user_address", "block_height"))`)
        await queryRunner.query(`INSERT INTO "temporary_likes"("post_txid", "user_address", "block_height") SELECT "post_txid", "user_address", "block_height" FROM "likes"`)
        await queryRunner.query(`DROP TABLE "likes"`)
        await queryRunner.query(`ALTER TABLE "temporary_likes" RENAME TO "likes"`)
        await queryRunner.query(`CREATE TABLE "temporary_user_blocks" ("blocker_address" text NOT NULL, "blocked_address" text NOT NULL, "block_height" bigint NOT NULL, CONSTRAINT "FK_7b9f27c64831150385f4cd2e2dc" FOREIGN KEY ("blocker_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_e07557b5ae3bf0c6a7b2e5df30e" FOREIGN KEY ("blocked_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_f2fc217f79fe6ebcc1f44350b4b" FOREIGN KEY ("block_height") REFERENCES "blocks" ("height") ON DELETE CASCADE, PRIMARY KEY ("blocker_address", "blocked_address", "block_height"))`)
        await queryRunner.query(`INSERT INTO "temporary_user_blocks"("blocker_address", "blocked_address", "block_height") SELECT "blocker_address", "blocked_address", "block_height" FROM "user_blocks"`)
        await queryRunner.query(`DROP TABLE "user_blocks"`)
        await queryRunner.query(`ALTER TABLE "temporary_user_blocks" RENAME TO "user_blocks"`)
        await queryRunner.query(`CREATE TABLE "temporary_follows" ("followed_address" text NOT NULL, "following_address" text NOT NULL, "block_height" bigint NOT NULL, CONSTRAINT "FK_896ecc3e22c5f3b9fe89e5f6699" FOREIGN KEY ("followed_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_f2b8ecc3180f97327685ffdd153" FOREIGN KEY ("following_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_b338ef5e9fc6b150226d4a45d8a" FOREIGN KEY ("block_height") REFERENCES "blocks" ("height") ON DELETE CASCADE, PRIMARY KEY ("followed_address", "following_address", "block_height"))`)
        await queryRunner.query(`INSERT INTO "temporary_follows"("followed_address", "following_address", "block_height") SELECT "followed_address", "following_address", "block_height" FROM "follows"`)
        await queryRunner.query(`DROP TABLE "follows"`)
        await queryRunner.query(`ALTER TABLE "temporary_follows" RENAME TO "follows"`)
        await queryRunner.query(`CREATE TABLE "temporary_flags" ("post_txid" text NOT NULL, "user_address" text NOT NULL, "block_height" bigint NOT NULL, CONSTRAINT "FK_d330f48942ea78a2a9df64c9965" FOREIGN KEY ("post_txid") REFERENCES "posts" ("txid") ON DELETE CASCADE, CONSTRAINT "FK_77d950f40f013776b34106746f9" FOREIGN KEY ("user_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_a835a80e9548be57833347706ea" FOREIGN KEY ("block_height") REFERENCES "blocks" ("height") ON DELETE CASCADE, PRIMARY KEY ("post_txid", "user_address", "block_height"))`)
        await queryRunner.query(`INSERT INTO "temporary_flags"("post_txid", "user_address", "block_height") SELECT "post_txid", "user_address", "block_height" FROM "flags"`)
        await queryRunner.query(`DROP TABLE "flags"`)
        await queryRunner.query(`ALTER TABLE "temporary_flags" RENAME TO "flags"`)
        await queryRunner.query(`CREATE TABLE "temporary_mentions" ("post_txid" text NOT NULL, "user_address" text NOT NULL, "block_height" bigint NOT NULL, CONSTRAINT "FK_f9278f3ddb4563dc57047a16fdd" FOREIGN KEY ("post_txid") REFERENCES "posts" ("txid") ON DELETE CASCADE, CONSTRAINT "FK_73bf803442939c9f00e57958b3f" FOREIGN KEY ("user_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_37a191c2d035d4776578ea2dbf6" FOREIGN KEY ("block_height") REFERENCES "blocks" ("height") ON DELETE CASCADE, PRIMARY KEY ("post_txid", "user_address", "block_height"))`)
        await queryRunner.query(`INSERT INTO "temporary_mentions"("post_txid", "user_address", "block_height") SELECT "post_txid", "user_address", "block_height" FROM "mentions"`)
        await queryRunner.query(`DROP TABLE "mentions"`)
        await queryRunner.query(`ALTER TABLE "temporary_mentions" RENAME TO "mentions"`)
        await queryRunner.query(`DROP INDEX "IDX_4149b5d28a9d574cb35ac0b880"`)
        await queryRunner.query(`DROP INDEX "IDX_2ccda451e12bc68c5af8d3c9b4"`)
        await queryRunner.query(`DROP INDEX "IDX_17be0dbba5ea05d3c431737ba8"`)
        await queryRunner.query(`DROP INDEX "IDX_617a3a43a298c164330279390c"`)
        await queryRunner.query(`DROP INDEX "IDX_1d57610e4bf65bca7df9f747be"`)
        await queryRunner.query(`DROP INDEX "IDX_d8dc419b6ee03babf580a7b3c3"`)
        await queryRunner.query(`DROP INDEX "IDX_08f49bf2cacd532e2e10eb5779"`)
        await queryRunner.query(`CREATE TABLE "temporary_orphans" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "nonce" integer, "position" integer, "type" text NOT NULL, "content" text, "reference_id" text, "reference_sender_address" text, "mentions" text, "sender_address" text, "block_height" bigint, CONSTRAINT "FK_d8dc419b6ee03babf580a7b3c30" FOREIGN KEY ("sender_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_08f49bf2cacd532e2e10eb57792" FOREIGN KEY ("block_height") REFERENCES "blocks" ("height") ON DELETE CASCADE)`)
        await queryRunner.query(`INSERT INTO "temporary_orphans"("txid", "created_at", "nonce", "position", "type", "content", "reference_id", "reference_sender_address", "mentions", "sender_address", "block_height") SELECT "txid", "created_at", "nonce", "position", "type", "content", "reference_id", "reference_sender_address", "mentions", "sender_address", "block_height" FROM "orphans"`)
        await queryRunner.query(`DROP TABLE "orphans"`)
        await queryRunner.query(`ALTER TABLE "temporary_orphans" RENAME TO "orphans"`)
        await queryRunner.query(`CREATE INDEX "IDX_4149b5d28a9d574cb35ac0b880" ON "orphans" ("created_at") `)
        await queryRunner.query(`CREATE INDEX "IDX_2ccda451e12bc68c5af8d3c9b4" ON "orphans" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_17be0dbba5ea05d3c431737ba8" ON "orphans" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_617a3a43a298c164330279390c" ON "orphans" ("reference_id") `)
        await queryRunner.query(`CREATE INDEX "IDX_1d57610e4bf65bca7df9f747be" ON "orphans" ("reference_sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_d8dc419b6ee03babf580a7b3c3" ON "orphans" ("sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_08f49bf2cacd532e2e10eb5779" ON "orphans" ("block_height") `)
        await queryRunner.query(`DROP INDEX "IDX_44ae61e72134027b2cc37050bd"`)
        await queryRunner.query(`CREATE TABLE "temporary_users" ("address" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "name" text NOT NULL, "bio" text, "avatar_link" text, "block_height" bigint, CONSTRAINT "FK_44ae61e72134027b2cc37050bd3" FOREIGN KEY ("block_height") REFERENCES "blocks" ("height") ON DELETE CASCADE)`)
        await queryRunner.query(`INSERT INTO "temporary_users"("address", "created_at", "name", "bio", "avatar_link", "block_height") SELECT "address", "created_at", "name", "bio", "avatar_link", "block_height" FROM "users"`)
        await queryRunner.query(`DROP TABLE "users"`)
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`)
        await queryRunner.query(`CREATE INDEX "IDX_44ae61e72134027b2cc37050bd" ON "users" ("block_height") `)
        await queryRunner.query(`DROP INDEX "IDX_8a2798743aa93a0242df71ceed"`)
        await queryRunner.query(`CREATE TABLE "temporary_tags" ("name" text PRIMARY KEY NOT NULL, "block_height" bigint, CONSTRAINT "FK_8a2798743aa93a0242df71ceed8" FOREIGN KEY ("block_height") REFERENCES "blocks" ("height") ON DELETE CASCADE)`)
        await queryRunner.query(`INSERT INTO "temporary_tags"("name", "block_height") SELECT "name", "block_height" FROM "tags"`)
        await queryRunner.query(`DROP TABLE "tags"`)
        await queryRunner.query(`ALTER TABLE "temporary_tags" RENAME TO "tags"`)
        await queryRunner.query(`CREATE INDEX "IDX_8a2798743aa93a0242df71ceed" ON "tags" ("block_height") `)
        await queryRunner.query(`CREATE TABLE "temporary_post_tags" ("post_txid" text NOT NULL, "tag_name" text NOT NULL, "block_height" bigint NOT NULL, CONSTRAINT "FK_2b73ad3de85484c053b3ffa0438" FOREIGN KEY ("post_txid") REFERENCES "posts" ("txid") ON DELETE CASCADE, CONSTRAINT "FK_400e719fd738123e7bcdae675a3" FOREIGN KEY ("tag_name") REFERENCES "tags" ("name") ON DELETE CASCADE, CONSTRAINT "FK_2ae1b2e25ef85c05a38d0c348f1" FOREIGN KEY ("block_height") REFERENCES "blocks" ("height") ON DELETE CASCADE, PRIMARY KEY ("post_txid", "tag_name", "block_height"))`)
        await queryRunner.query(`INSERT INTO "temporary_post_tags"("post_txid", "tag_name", "block_height") SELECT "post_txid", "tag_name", "block_height" FROM "post_tags"`)
        await queryRunner.query(`DROP TABLE "post_tags"`)
        await queryRunner.query(`ALTER TABLE "temporary_post_tags" RENAME TO "post_tags"`)
        await queryRunner.query(`DROP INDEX "IDX_60818528127866f5002e7f826d"`)
        await queryRunner.query(`DROP INDEX "IDX_862deee3599ab1a65f8d6a4845"`)
        await queryRunner.query(`DROP INDEX "IDX_560752d45d78a3332853345e32"`)
        await queryRunner.query(`DROP INDEX "IDX_5e9b13dbe0048d25c4b87d5b67"`)
        await queryRunner.query(`DROP INDEX "IDX_a56e2db14676f90be1694e2723"`)
        await queryRunner.query(`DROP INDEX "IDX_565d3e71ac2ea22a54a0631994"`)
        await queryRunner.query(`CREATE TABLE "temporary_posts" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "deleted_at" datetime, "nonce" integer NOT NULL, "position" integer NOT NULL, "type" text NOT NULL, "content" text, "block_height" bigint, "parent_txid" text, "sender_address" text, CONSTRAINT "FK_5e9b13dbe0048d25c4b87d5b676" FOREIGN KEY ("block_height") REFERENCES "blocks" ("height") ON DELETE CASCADE, CONSTRAINT "FK_a56e2db14676f90be1694e27235" FOREIGN KEY ("parent_txid") REFERENCES "posts" ("txid"), CONSTRAINT "FK_565d3e71ac2ea22a54a0631994b" FOREIGN KEY ("sender_address") REFERENCES "users" ("address") ON DELETE CASCADE)`)
        await queryRunner.query(`INSERT INTO "temporary_posts"("txid", "created_at", "deleted_at", "nonce", "position", "type", "content", "block_height", "parent_txid", "sender_address") SELECT "txid", "created_at", "deleted_at", "nonce", "position", "type", "content", "block_height", "parent_txid", "sender_address" FROM "posts"`)
        await queryRunner.query(`DROP TABLE "posts"`)
        await queryRunner.query(`ALTER TABLE "temporary_posts" RENAME TO "posts"`)
        await queryRunner.query(`CREATE INDEX "IDX_60818528127866f5002e7f826d" ON "posts" ("created_at") `)
        await queryRunner.query(`CREATE INDEX "IDX_862deee3599ab1a65f8d6a4845" ON "posts" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_560752d45d78a3332853345e32" ON "posts" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_5e9b13dbe0048d25c4b87d5b67" ON "posts" ("block_height") `)
        await queryRunner.query(`CREATE INDEX "IDX_a56e2db14676f90be1694e2723" ON "posts" ("parent_txid") `)
        await queryRunner.query(`CREATE INDEX "IDX_565d3e71ac2ea22a54a0631994" ON "posts" ("sender_address") `)
        await queryRunner.query(`DROP INDEX "IDX_7ee003620e5c4dc41c8020c3a4"`)
        await queryRunner.query(`DROP INDEX "IDX_f4ddf5596761915d4415c18040"`)
        await queryRunner.query(`CREATE TABLE "temporary_utxos" ("txid" text NOT NULL, "position" integer NOT NULL, "address" text NOT NULL, "value" bigint NOT NULL, "raw" text NOT NULL, "block_height" bigint, CONSTRAINT "FK_f4ddf5596761915d4415c180400" FOREIGN KEY ("block_height") REFERENCES "blocks" ("height") ON DELETE CASCADE, PRIMARY KEY ("txid", "position"))`)
        await queryRunner.query(`INSERT INTO "temporary_utxos"("txid", "position", "address", "value", "raw", "block_height") SELECT "txid", "position", "address", "value", "raw", "block_height" FROM "utxos"`)
        await queryRunner.query(`DROP TABLE "utxos"`)
        await queryRunner.query(`ALTER TABLE "temporary_utxos" RENAME TO "utxos"`)
        await queryRunner.query(`CREATE INDEX "IDX_7ee003620e5c4dc41c8020c3a4" ON "utxos" ("address") `)
        await queryRunner.query(`CREATE INDEX "IDX_f4ddf5596761915d4415c18040" ON "utxos" ("block_height") `)
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`DROP INDEX "IDX_f4ddf5596761915d4415c18040"`)
        await queryRunner.query(`DROP INDEX "IDX_7ee003620e5c4dc41c8020c3a4"`)
        await queryRunner.query(`ALTER TABLE "utxos" RENAME TO "temporary_utxos"`)
        await queryRunner.query(`CREATE TABLE "utxos" ("txid" text NOT NULL, "position" integer NOT NULL, "address" text NOT NULL, "value" bigint NOT NULL, "raw" text NOT NULL, "block_height" bigint, PRIMARY KEY ("txid", "position"))`)
        await queryRunner.query(`INSERT INTO "utxos"("txid", "position", "address", "value", "raw", "block_height") SELECT "txid", "position", "address", "value", "raw", "block_height" FROM "temporary_utxos"`)
        await queryRunner.query(`DROP TABLE "temporary_utxos"`)
        await queryRunner.query(`CREATE INDEX "IDX_f4ddf5596761915d4415c18040" ON "utxos" ("block_height") `)
        await queryRunner.query(`CREATE INDEX "IDX_7ee003620e5c4dc41c8020c3a4" ON "utxos" ("address") `)
        await queryRunner.query(`DROP INDEX "IDX_565d3e71ac2ea22a54a0631994"`)
        await queryRunner.query(`DROP INDEX "IDX_a56e2db14676f90be1694e2723"`)
        await queryRunner.query(`DROP INDEX "IDX_5e9b13dbe0048d25c4b87d5b67"`)
        await queryRunner.query(`DROP INDEX "IDX_560752d45d78a3332853345e32"`)
        await queryRunner.query(`DROP INDEX "IDX_862deee3599ab1a65f8d6a4845"`)
        await queryRunner.query(`DROP INDEX "IDX_60818528127866f5002e7f826d"`)
        await queryRunner.query(`ALTER TABLE "posts" RENAME TO "temporary_posts"`)
        await queryRunner.query(`CREATE TABLE "posts" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "deleted_at" datetime, "nonce" integer NOT NULL, "position" integer NOT NULL, "type" text NOT NULL, "content" text, "block_height" bigint, "parent_txid" text, "sender_address" text)`)
        await queryRunner.query(`INSERT INTO "posts"("txid", "created_at", "deleted_at", "nonce", "position", "type", "content", "block_height", "parent_txid", "sender_address") SELECT "txid", "created_at", "deleted_at", "nonce", "position", "type", "content", "block_height", "parent_txid", "sender_address" FROM "temporary_posts"`)
        await queryRunner.query(`DROP TABLE "temporary_posts"`)
        await queryRunner.query(`CREATE INDEX "IDX_565d3e71ac2ea22a54a0631994" ON "posts" ("sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_a56e2db14676f90be1694e2723" ON "posts" ("parent_txid") `)
        await queryRunner.query(`CREATE INDEX "IDX_5e9b13dbe0048d25c4b87d5b67" ON "posts" ("block_height") `)
        await queryRunner.query(`CREATE INDEX "IDX_560752d45d78a3332853345e32" ON "posts" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_862deee3599ab1a65f8d6a4845" ON "posts" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_60818528127866f5002e7f826d" ON "posts" ("created_at") `)
        await queryRunner.query(`ALTER TABLE "post_tags" RENAME TO "temporary_post_tags"`)
        await queryRunner.query(`CREATE TABLE "post_tags" ("post_txid" text NOT NULL, "tag_name" text NOT NULL, "block_height" bigint NOT NULL, PRIMARY KEY ("post_txid", "tag_name", "block_height"))`)
        await queryRunner.query(`INSERT INTO "post_tags"("post_txid", "tag_name", "block_height") SELECT "post_txid", "tag_name", "block_height" FROM "temporary_post_tags"`)
        await queryRunner.query(`DROP TABLE "temporary_post_tags"`)
        await queryRunner.query(`DROP INDEX "IDX_8a2798743aa93a0242df71ceed"`)
        await queryRunner.query(`ALTER TABLE "tags" RENAME TO "temporary_tags"`)
        await queryRunner.query(`CREATE TABLE "tags" ("name" text PRIMARY KEY NOT NULL, "block_height" bigint)`)
        await queryRunner.query(`INSERT INTO "tags"("name", "block_height") SELECT "name", "block_height" FROM "temporary_tags"`)
        await queryRunner.query(`DROP TABLE "temporary_tags"`)
        await queryRunner.query(`CREATE INDEX "IDX_8a2798743aa93a0242df71ceed" ON "tags" ("block_height") `)
        await queryRunner.query(`DROP INDEX "IDX_44ae61e72134027b2cc37050bd"`)
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`)
        await queryRunner.query(`CREATE TABLE "users" ("address" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "name" text NOT NULL, "bio" text, "avatar_link" text, "block_height" bigint)`)
        await queryRunner.query(`INSERT INTO "users"("address", "created_at", "name", "bio", "avatar_link", "block_height") SELECT "address", "created_at", "name", "bio", "avatar_link", "block_height" FROM "temporary_users"`)
        await queryRunner.query(`DROP TABLE "temporary_users"`)
        await queryRunner.query(`CREATE INDEX "IDX_44ae61e72134027b2cc37050bd" ON "users" ("block_height") `)
        await queryRunner.query(`DROP INDEX "IDX_08f49bf2cacd532e2e10eb5779"`)
        await queryRunner.query(`DROP INDEX "IDX_d8dc419b6ee03babf580a7b3c3"`)
        await queryRunner.query(`DROP INDEX "IDX_1d57610e4bf65bca7df9f747be"`)
        await queryRunner.query(`DROP INDEX "IDX_617a3a43a298c164330279390c"`)
        await queryRunner.query(`DROP INDEX "IDX_17be0dbba5ea05d3c431737ba8"`)
        await queryRunner.query(`DROP INDEX "IDX_2ccda451e12bc68c5af8d3c9b4"`)
        await queryRunner.query(`DROP INDEX "IDX_4149b5d28a9d574cb35ac0b880"`)
        await queryRunner.query(`ALTER TABLE "orphans" RENAME TO "temporary_orphans"`)
        await queryRunner.query(`CREATE TABLE "orphans" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "nonce" integer, "position" integer, "type" text NOT NULL, "content" text, "reference_id" text, "reference_sender_address" text, "mentions" text, "sender_address" text, "block_height" bigint)`)
        await queryRunner.query(`INSERT INTO "orphans"("txid", "created_at", "nonce", "position", "type", "content", "reference_id", "reference_sender_address", "mentions", "sender_address", "block_height") SELECT "txid", "created_at", "nonce", "position", "type", "content", "reference_id", "reference_sender_address", "mentions", "sender_address", "block_height" FROM "temporary_orphans"`)
        await queryRunner.query(`DROP TABLE "temporary_orphans"`)
        await queryRunner.query(`CREATE INDEX "IDX_08f49bf2cacd532e2e10eb5779" ON "orphans" ("block_height") `)
        await queryRunner.query(`CREATE INDEX "IDX_d8dc419b6ee03babf580a7b3c3" ON "orphans" ("sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_1d57610e4bf65bca7df9f747be" ON "orphans" ("reference_sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_617a3a43a298c164330279390c" ON "orphans" ("reference_id") `)
        await queryRunner.query(`CREATE INDEX "IDX_17be0dbba5ea05d3c431737ba8" ON "orphans" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_2ccda451e12bc68c5af8d3c9b4" ON "orphans" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_4149b5d28a9d574cb35ac0b880" ON "orphans" ("created_at") `)
        await queryRunner.query(`ALTER TABLE "mentions" RENAME TO "temporary_mentions"`)
        await queryRunner.query(`CREATE TABLE "mentions" ("post_txid" text NOT NULL, "user_address" text NOT NULL, "block_height" bigint NOT NULL, PRIMARY KEY ("post_txid", "user_address", "block_height"))`)
        await queryRunner.query(`INSERT INTO "mentions"("post_txid", "user_address", "block_height") SELECT "post_txid", "user_address", "block_height" FROM "temporary_mentions"`)
        await queryRunner.query(`DROP TABLE "temporary_mentions"`)
        await queryRunner.query(`ALTER TABLE "flags" RENAME TO "temporary_flags"`)
        await queryRunner.query(`CREATE TABLE "flags" ("post_txid" text NOT NULL, "user_address" text NOT NULL, "block_height" bigint NOT NULL, PRIMARY KEY ("post_txid", "user_address", "block_height"))`)
        await queryRunner.query(`INSERT INTO "flags"("post_txid", "user_address", "block_height") SELECT "post_txid", "user_address", "block_height" FROM "temporary_flags"`)
        await queryRunner.query(`DROP TABLE "temporary_flags"`)
        await queryRunner.query(`ALTER TABLE "follows" RENAME TO "temporary_follows"`)
        await queryRunner.query(`CREATE TABLE "follows" ("followed_address" text NOT NULL, "following_address" text NOT NULL, "block_height" bigint NOT NULL, PRIMARY KEY ("followed_address", "following_address", "block_height"))`)
        await queryRunner.query(`INSERT INTO "follows"("followed_address", "following_address", "block_height") SELECT "followed_address", "following_address", "block_height" FROM "temporary_follows"`)
        await queryRunner.query(`DROP TABLE "temporary_follows"`)
        await queryRunner.query(`ALTER TABLE "user_blocks" RENAME TO "temporary_user_blocks"`)
        await queryRunner.query(`CREATE TABLE "user_blocks" ("blocker_address" text NOT NULL, "blocked_address" text NOT NULL, "block_height" bigint NOT NULL, PRIMARY KEY ("blocker_address", "blocked_address", "block_height"))`)
        await queryRunner.query(`INSERT INTO "user_blocks"("blocker_address", "blocked_address", "block_height") SELECT "blocker_address", "blocked_address", "block_height" FROM "temporary_user_blocks"`)
        await queryRunner.query(`DROP TABLE "temporary_user_blocks"`)
        await queryRunner.query(`ALTER TABLE "likes" RENAME TO "temporary_likes"`)
        await queryRunner.query(`CREATE TABLE "likes" ("post_txid" text NOT NULL, "user_address" text NOT NULL, "block_height" bigint NOT NULL, PRIMARY KEY ("post_txid", "user_address", "block_height"))`)
        await queryRunner.query(`INSERT INTO "likes"("post_txid", "user_address", "block_height") SELECT "post_txid", "user_address", "block_height" FROM "temporary_likes"`)
        await queryRunner.query(`DROP TABLE "temporary_likes"`)
        await queryRunner.query(`DROP INDEX "IDX_00d4f3eb491f00ae5bece2a559"`)
        await queryRunner.query(`DROP TABLE "blocks"`)
        await queryRunner.query(`DROP INDEX "IDX_f4ddf5596761915d4415c18040"`)
        await queryRunner.query(`DROP INDEX "IDX_7ee003620e5c4dc41c8020c3a4"`)
        await queryRunner.query(`DROP TABLE "utxos"`)
        await queryRunner.query(`DROP INDEX "IDX_565d3e71ac2ea22a54a0631994"`)
        await queryRunner.query(`DROP INDEX "IDX_a56e2db14676f90be1694e2723"`)
        await queryRunner.query(`DROP INDEX "IDX_5e9b13dbe0048d25c4b87d5b67"`)
        await queryRunner.query(`DROP INDEX "IDX_560752d45d78a3332853345e32"`)
        await queryRunner.query(`DROP INDEX "IDX_862deee3599ab1a65f8d6a4845"`)
        await queryRunner.query(`DROP INDEX "IDX_60818528127866f5002e7f826d"`)
        await queryRunner.query(`DROP TABLE "posts"`)
        await queryRunner.query(`DROP TABLE "post_tags"`)
        await queryRunner.query(`DROP INDEX "IDX_8a2798743aa93a0242df71ceed"`)
        await queryRunner.query(`DROP TABLE "tags"`)
        await queryRunner.query(`DROP INDEX "IDX_44ae61e72134027b2cc37050bd"`)
        await queryRunner.query(`DROP TABLE "users"`)
        await queryRunner.query(`DROP INDEX "IDX_08f49bf2cacd532e2e10eb5779"`)
        await queryRunner.query(`DROP INDEX "IDX_d8dc419b6ee03babf580a7b3c3"`)
        await queryRunner.query(`DROP INDEX "IDX_1d57610e4bf65bca7df9f747be"`)
        await queryRunner.query(`DROP INDEX "IDX_617a3a43a298c164330279390c"`)
        await queryRunner.query(`DROP INDEX "IDX_17be0dbba5ea05d3c431737ba8"`)
        await queryRunner.query(`DROP INDEX "IDX_2ccda451e12bc68c5af8d3c9b4"`)
        await queryRunner.query(`DROP INDEX "IDX_4149b5d28a9d574cb35ac0b880"`)
        await queryRunner.query(`DROP TABLE "orphans"`)
        await queryRunner.query(`DROP TABLE "mentions"`)
        await queryRunner.query(`DROP TABLE "flags"`)
        await queryRunner.query(`DROP TABLE "follows"`)
        await queryRunner.query(`DROP TABLE "user_blocks"`)
        await queryRunner.query(`DROP TABLE "likes"`)
    }

}
