import { MigrationInterface, QueryRunner } from 'typeorm'

export class Init1561693627435 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`CREATE TABLE "orphans" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "block_height" bigint NOT NULL, "nonce" integer NOT NULL, "position" integer NOT NULL, "content" text NOT NULL, "mentions" text, "tags" text, "sender_address" text)`)
        await queryRunner.query(`CREATE INDEX "IDX_4149b5d28a9d574cb35ac0b880" ON "orphans" ("created_at") `)
        await queryRunner.query(`CREATE INDEX "IDX_08f49bf2cacd532e2e10eb5779" ON "orphans" ("block_height") `)
        await queryRunner.query(`CREATE INDEX "IDX_f82c6e777d47e511b97334fe45" ON "orphans" ("nonce") `)
        await queryRunner.query(`CREATE INDEX "IDX_2ccda451e12bc68c5af8d3c9b4" ON "orphans" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_d8dc419b6ee03babf580a7b3c3" ON "orphans" ("sender_address") `)
        await queryRunner.query(`CREATE TABLE "users" ("address" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "birth_block" bigint NOT NULL, "name" text NOT NULL, "bio" text, "avatar_link" text)`)
        await queryRunner.query(`CREATE INDEX "IDX_1b4832240d11291453c40c3281" ON "users" ("birth_block") `)
        await queryRunner.query(`CREATE TABLE "tags" ("name" text PRIMARY KEY NOT NULL)`)
        await queryRunner.query(`CREATE TABLE "borks" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "deleted_at" datetime, "type" text NOT NULL, "nonce" integer, "position" integer, "content" text, "sender_address" text, "parent_txid" text, "recipient_address" text)`)
        await queryRunner.query(`CREATE INDEX "IDX_225c8d7a66d2e44dc46bff2b89" ON "borks" ("created_at") `)
        await queryRunner.query(`CREATE INDEX "IDX_b556e61d2d0907016c8ee58465" ON "borks" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_000418d2fa57716c62e77f7cb9" ON "borks" ("nonce") `)
        await queryRunner.query(`CREATE INDEX "IDX_f1d79da8758a51316b819cc38a" ON "borks" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_6d695ba01f87a7cefa3617a85c" ON "borks" ("sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_2873c3b06729583654b6b70fe9" ON "borks" ("parent_txid") `)
        await queryRunner.query(`CREATE INDEX "IDX_e4d51394b5757b0d74482ab356" ON "borks" ("recipient_address") `)
        await queryRunner.query(`CREATE TABLE "tx_blocks" ("height" bigint PRIMARY KEY NOT NULL, "hash" text NOT NULL, CONSTRAINT "UQ_d16046b3c22e0ac37b9367ba8d4" UNIQUE ("hash"))`)
        await queryRunner.query(`CREATE INDEX "IDX_d16046b3c22e0ac37b9367ba8d" ON "tx_blocks" ("hash") `)
        await queryRunner.query(`CREATE TABLE "mentions" ("user_address" text NOT NULL, "bork_txid" text NOT NULL, PRIMARY KEY ("user_address", "bork_txid"))`)
        await queryRunner.query(`CREATE TABLE "bork_tags" ("tag_name" text NOT NULL, "bork_txid" text NOT NULL, PRIMARY KEY ("tag_name", "bork_txid"))`)
        await queryRunner.query(`DROP INDEX "IDX_4149b5d28a9d574cb35ac0b880"`)
        await queryRunner.query(`DROP INDEX "IDX_08f49bf2cacd532e2e10eb5779"`)
        await queryRunner.query(`DROP INDEX "IDX_f82c6e777d47e511b97334fe45"`)
        await queryRunner.query(`DROP INDEX "IDX_2ccda451e12bc68c5af8d3c9b4"`)
        await queryRunner.query(`DROP INDEX "IDX_d8dc419b6ee03babf580a7b3c3"`)
        await queryRunner.query(`CREATE TABLE "temporary_orphans" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "block_height" bigint NOT NULL, "nonce" integer NOT NULL, "position" integer NOT NULL, "content" text NOT NULL, "mentions" text, "tags" text, "sender_address" text, CONSTRAINT "FK_d8dc419b6ee03babf580a7b3c30" FOREIGN KEY ("sender_address") REFERENCES "users" ("address"))`)
        await queryRunner.query(`INSERT INTO "temporary_orphans"("txid", "created_at", "block_height", "nonce", "position", "content", "mentions", "tags", "sender_address") SELECT "txid", "created_at", "block_height", "nonce", "position", "content", "mentions", "tags", "sender_address" FROM "orphans"`)
        await queryRunner.query(`DROP TABLE "orphans"`)
        await queryRunner.query(`ALTER TABLE "temporary_orphans" RENAME TO "orphans"`)
        await queryRunner.query(`CREATE INDEX "IDX_4149b5d28a9d574cb35ac0b880" ON "orphans" ("created_at") `)
        await queryRunner.query(`CREATE INDEX "IDX_08f49bf2cacd532e2e10eb5779" ON "orphans" ("block_height") `)
        await queryRunner.query(`CREATE INDEX "IDX_f82c6e777d47e511b97334fe45" ON "orphans" ("nonce") `)
        await queryRunner.query(`CREATE INDEX "IDX_2ccda451e12bc68c5af8d3c9b4" ON "orphans" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_d8dc419b6ee03babf580a7b3c3" ON "orphans" ("sender_address") `)
        await queryRunner.query(`DROP INDEX "IDX_225c8d7a66d2e44dc46bff2b89"`)
        await queryRunner.query(`DROP INDEX "IDX_b556e61d2d0907016c8ee58465"`)
        await queryRunner.query(`DROP INDEX "IDX_000418d2fa57716c62e77f7cb9"`)
        await queryRunner.query(`DROP INDEX "IDX_f1d79da8758a51316b819cc38a"`)
        await queryRunner.query(`DROP INDEX "IDX_6d695ba01f87a7cefa3617a85c"`)
        await queryRunner.query(`DROP INDEX "IDX_2873c3b06729583654b6b70fe9"`)
        await queryRunner.query(`DROP INDEX "IDX_e4d51394b5757b0d74482ab356"`)
        await queryRunner.query(`CREATE TABLE "temporary_borks" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "deleted_at" datetime, "type" text NOT NULL, "nonce" integer, "position" integer, "content" text, "sender_address" text, "parent_txid" text, "recipient_address" text, CONSTRAINT "FK_6d695ba01f87a7cefa3617a85cd" FOREIGN KEY ("sender_address") REFERENCES "users" ("address"), CONSTRAINT "FK_2873c3b06729583654b6b70fe97" FOREIGN KEY ("parent_txid") REFERENCES "borks" ("txid"), CONSTRAINT "FK_e4d51394b5757b0d74482ab3561" FOREIGN KEY ("recipient_address") REFERENCES "users" ("address"))`)
        await queryRunner.query(`INSERT INTO "temporary_borks"("txid", "created_at", "deleted_at", "type", "nonce", "position", "content", "sender_address", "parent_txid", "recipient_address") SELECT "txid", "created_at", "deleted_at", "type", "nonce", "position", "content", "sender_address", "parent_txid", "recipient_address" FROM "borks"`)
        await queryRunner.query(`DROP TABLE "borks"`)
        await queryRunner.query(`ALTER TABLE "temporary_borks" RENAME TO "borks"`)
        await queryRunner.query(`CREATE INDEX "IDX_225c8d7a66d2e44dc46bff2b89" ON "borks" ("created_at") `)
        await queryRunner.query(`CREATE INDEX "IDX_b556e61d2d0907016c8ee58465" ON "borks" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_000418d2fa57716c62e77f7cb9" ON "borks" ("nonce") `)
        await queryRunner.query(`CREATE INDEX "IDX_f1d79da8758a51316b819cc38a" ON "borks" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_6d695ba01f87a7cefa3617a85c" ON "borks" ("sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_2873c3b06729583654b6b70fe9" ON "borks" ("parent_txid") `)
        await queryRunner.query(`CREATE INDEX "IDX_e4d51394b5757b0d74482ab356" ON "borks" ("recipient_address") `)
        await queryRunner.query(`CREATE TABLE "temporary_mentions" ("user_address" text NOT NULL, "bork_txid" text NOT NULL, CONSTRAINT "FK_73bf803442939c9f00e57958b3f" FOREIGN KEY ("user_address") REFERENCES "users" ("address") ON DELETE CASCADE, CONSTRAINT "FK_62b455467870e6f35a1d3d1e041" FOREIGN KEY ("bork_txid") REFERENCES "borks" ("txid") ON DELETE CASCADE, PRIMARY KEY ("user_address", "bork_txid"))`)
        await queryRunner.query(`INSERT INTO "temporary_mentions"("user_address", "bork_txid") SELECT "user_address", "bork_txid" FROM "mentions"`)
        await queryRunner.query(`DROP TABLE "mentions"`)
        await queryRunner.query(`ALTER TABLE "temporary_mentions" RENAME TO "mentions"`)
        await queryRunner.query(`CREATE TABLE "temporary_bork_tags" ("tag_name" text NOT NULL, "bork_txid" text NOT NULL, CONSTRAINT "FK_dd1d937e3d78d4e405b6f3f41e6" FOREIGN KEY ("tag_name") REFERENCES "tags" ("name") ON DELETE CASCADE, CONSTRAINT "FK_1a4840b35d90022c563a37326ff" FOREIGN KEY ("bork_txid") REFERENCES "borks" ("txid") ON DELETE CASCADE, PRIMARY KEY ("tag_name", "bork_txid"))`)
        await queryRunner.query(`INSERT INTO "temporary_bork_tags"("tag_name", "bork_txid") SELECT "tag_name", "bork_txid" FROM "bork_tags"`)
        await queryRunner.query(`DROP TABLE "bork_tags"`)
        await queryRunner.query(`ALTER TABLE "temporary_bork_tags" RENAME TO "bork_tags"`)
    }

    public async down(queryRunner: QueryRunner): Promise<any> {
        await queryRunner.query(`ALTER TABLE "bork_tags" RENAME TO "temporary_bork_tags"`)
        await queryRunner.query(`CREATE TABLE "bork_tags" ("tag_name" text NOT NULL, "bork_txid" text NOT NULL, PRIMARY KEY ("tag_name", "bork_txid"))`)
        await queryRunner.query(`INSERT INTO "bork_tags"("tag_name", "bork_txid") SELECT "tag_name", "bork_txid" FROM "temporary_bork_tags"`)
        await queryRunner.query(`DROP TABLE "temporary_bork_tags"`)
        await queryRunner.query(`ALTER TABLE "mentions" RENAME TO "temporary_mentions"`)
        await queryRunner.query(`CREATE TABLE "mentions" ("user_address" text NOT NULL, "bork_txid" text NOT NULL, PRIMARY KEY ("user_address", "bork_txid"))`)
        await queryRunner.query(`INSERT INTO "mentions"("user_address", "bork_txid") SELECT "user_address", "bork_txid" FROM "temporary_mentions"`)
        await queryRunner.query(`DROP TABLE "temporary_mentions"`)
        await queryRunner.query(`DROP INDEX "IDX_e4d51394b5757b0d74482ab356"`)
        await queryRunner.query(`DROP INDEX "IDX_2873c3b06729583654b6b70fe9"`)
        await queryRunner.query(`DROP INDEX "IDX_6d695ba01f87a7cefa3617a85c"`)
        await queryRunner.query(`DROP INDEX "IDX_f1d79da8758a51316b819cc38a"`)
        await queryRunner.query(`DROP INDEX "IDX_000418d2fa57716c62e77f7cb9"`)
        await queryRunner.query(`DROP INDEX "IDX_b556e61d2d0907016c8ee58465"`)
        await queryRunner.query(`DROP INDEX "IDX_225c8d7a66d2e44dc46bff2b89"`)
        await queryRunner.query(`ALTER TABLE "borks" RENAME TO "temporary_borks"`)
        await queryRunner.query(`CREATE TABLE "borks" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "deleted_at" datetime, "type" text NOT NULL, "nonce" integer, "position" integer, "content" text, "sender_address" text, "parent_txid" text, "recipient_address" text)`)
        await queryRunner.query(`INSERT INTO "borks"("txid", "created_at", "deleted_at", "type", "nonce", "position", "content", "sender_address", "parent_txid", "recipient_address") SELECT "txid", "created_at", "deleted_at", "type", "nonce", "position", "content", "sender_address", "parent_txid", "recipient_address" FROM "temporary_borks"`)
        await queryRunner.query(`DROP TABLE "temporary_borks"`)
        await queryRunner.query(`CREATE INDEX "IDX_e4d51394b5757b0d74482ab356" ON "borks" ("recipient_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_2873c3b06729583654b6b70fe9" ON "borks" ("parent_txid") `)
        await queryRunner.query(`CREATE INDEX "IDX_6d695ba01f87a7cefa3617a85c" ON "borks" ("sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_f1d79da8758a51316b819cc38a" ON "borks" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_000418d2fa57716c62e77f7cb9" ON "borks" ("nonce") `)
        await queryRunner.query(`CREATE INDEX "IDX_b556e61d2d0907016c8ee58465" ON "borks" ("type") `)
        await queryRunner.query(`CREATE INDEX "IDX_225c8d7a66d2e44dc46bff2b89" ON "borks" ("created_at") `)
        await queryRunner.query(`DROP INDEX "IDX_d8dc419b6ee03babf580a7b3c3"`)
        await queryRunner.query(`DROP INDEX "IDX_2ccda451e12bc68c5af8d3c9b4"`)
        await queryRunner.query(`DROP INDEX "IDX_f82c6e777d47e511b97334fe45"`)
        await queryRunner.query(`DROP INDEX "IDX_08f49bf2cacd532e2e10eb5779"`)
        await queryRunner.query(`DROP INDEX "IDX_4149b5d28a9d574cb35ac0b880"`)
        await queryRunner.query(`ALTER TABLE "orphans" RENAME TO "temporary_orphans"`)
        await queryRunner.query(`CREATE TABLE "orphans" ("txid" text PRIMARY KEY NOT NULL, "created_at" datetime NOT NULL, "block_height" bigint NOT NULL, "nonce" integer NOT NULL, "position" integer NOT NULL, "content" text NOT NULL, "mentions" text, "tags" text, "sender_address" text)`)
        await queryRunner.query(`INSERT INTO "orphans"("txid", "created_at", "block_height", "nonce", "position", "content", "mentions", "tags", "sender_address") SELECT "txid", "created_at", "block_height", "nonce", "position", "content", "mentions", "tags", "sender_address" FROM "temporary_orphans"`)
        await queryRunner.query(`DROP TABLE "temporary_orphans"`)
        await queryRunner.query(`CREATE INDEX "IDX_d8dc419b6ee03babf580a7b3c3" ON "orphans" ("sender_address") `)
        await queryRunner.query(`CREATE INDEX "IDX_2ccda451e12bc68c5af8d3c9b4" ON "orphans" ("position") `)
        await queryRunner.query(`CREATE INDEX "IDX_f82c6e777d47e511b97334fe45" ON "orphans" ("nonce") `)
        await queryRunner.query(`CREATE INDEX "IDX_08f49bf2cacd532e2e10eb5779" ON "orphans" ("block_height") `)
        await queryRunner.query(`CREATE INDEX "IDX_4149b5d28a9d574cb35ac0b880" ON "orphans" ("created_at") `)
        await queryRunner.query(`DROP TABLE "bork_tags"`)
        await queryRunner.query(`DROP TABLE "mentions"`)
        await queryRunner.query(`DROP INDEX "IDX_d16046b3c22e0ac37b9367ba8d"`)
        await queryRunner.query(`DROP TABLE "tx_blocks"`)
        await queryRunner.query(`DROP INDEX "IDX_e4d51394b5757b0d74482ab356"`)
        await queryRunner.query(`DROP INDEX "IDX_2873c3b06729583654b6b70fe9"`)
        await queryRunner.query(`DROP INDEX "IDX_6d695ba01f87a7cefa3617a85c"`)
        await queryRunner.query(`DROP INDEX "IDX_f1d79da8758a51316b819cc38a"`)
        await queryRunner.query(`DROP INDEX "IDX_000418d2fa57716c62e77f7cb9"`)
        await queryRunner.query(`DROP INDEX "IDX_b556e61d2d0907016c8ee58465"`)
        await queryRunner.query(`DROP INDEX "IDX_225c8d7a66d2e44dc46bff2b89"`)
        await queryRunner.query(`DROP TABLE "borks"`)
        await queryRunner.query(`DROP TABLE "tags"`)
        await queryRunner.query(`DROP INDEX "IDX_1b4832240d11291453c40c3281"`)
        await queryRunner.query(`DROP TABLE "users"`)
        await queryRunner.query(`DROP INDEX "IDX_d8dc419b6ee03babf580a7b3c3"`)
        await queryRunner.query(`DROP INDEX "IDX_2ccda451e12bc68c5af8d3c9b4"`)
        await queryRunner.query(`DROP INDEX "IDX_f82c6e777d47e511b97334fe45"`)
        await queryRunner.query(`DROP INDEX "IDX_08f49bf2cacd532e2e10eb5779"`)
        await queryRunner.query(`DROP INDEX "IDX_4149b5d28a9d574cb35ac0b880"`)
        await queryRunner.query(`DROP TABLE "orphans"`)
    }

}
